### ISSUE TITLE
Shields disappear

### ISSUE THREAD

**Issue by jarredr** [Jakllp/war#6]
Issue:
The war plugin leads to shields being buggy both within warzones and outside of them on the whole server. If you equip a shield, then change the item that is in your right hand, the shield disappears. It also seems that there is no way to create a warzone loadout with a shield equipped.
This is with the option swordblocking:false selected in the config.

Environment:
- paper-1.17.1-109
- worldedit-bukkit-7.2.6-beta-01
- war-2.9.0

**Comment by Jakllp** [comment]
This is a bug - Will be fixed soon

**Comment by Jakllp** [comment]
Both problems have been fixed in [v2.9.1](https://github.com/Jakllp/war/releases/tag/v2.9.1)
