### ISSUE TITLE
Environmental damage applies very quickly

### ISSUE THREAD

**Issue by jarredr** [Jakllp/war#7]
Issue:
The config option rapiddamage is enabled by default and it causes environmental damage such as lava and cactus to apply extremely quickly. Is this intended?

Environment:
- paper-1.17.1-109
- worldedit-bukkit-7.2.6-beta-01
- war-2.9.0

**Comment by Jakllp** [comment]
It's basically a limitation of the damage system of minecraft. If you want rapid fire weapons to work you need to lower the amount of ticks during which the player can't take damage which causes this. 

I might however set the default to false - good call

**Comment by Jakllp** [comment]
Default is now false - [v2.9.1](https://github.com/Jakllp/war/releases/tag/v2.9.1)

Added a disclaimer in [Wiki-Entry](https://github.com/Jakllp/war/wiki/Warzone-Config)

**Comment by Jakllp** [comment]
Default is now false - [v2.9.1](https://github.com/Jakllp/war/releases/tag/v2.9.1)

Added a note in [Wiki-Entry](https://github.com/Jakllp/war/wiki/Warzone-Config)
