### ISSUE TITLE
IllegalArgumentException on server start

### ISSUE THREAD

**Issue by JacksonWillford** [Jakllp/war#9]
Stacktrace:
https://i.imgur.com/AlbzCVW.png

Do you need me to provide the configuration?

**Comment by Jakllp** [comment]
So this happened on server-start? Interesting (the stacktrace actually happened on disable but nonetheless there is a bug there)

Quick question: Did you recently upgrade to a 1.17.1? If so: From what Minecraft-Version?

**Comment by JacksonWillford** [comment]
Hello! Sorry for the delay, this is happening on server shutdown, not startup. And yes, we upgraded from 1.16.5 to 1.17.1.

**Comment by Jakllp** [comment]
Hi, no problem

I suspected it to be that bug but this should be a fairly easy fix

Only a few steps:
- PLEASE backup the "dat"-folder in the war-folder
- Start the server
- Go to a zone (don't enter it through a portal) and make sure its blocks are like you want them to be
- Do `/savezone zoneName` for that zone
- Repeat the previous two steps  

**Also: DON'T use /resetzone before you haven't saved a zone**

That should theoretically fix the issue.
If it doesn't I'll have to look into your case further but this isn't a general bug just some compatibility stuff.


Explanation:
The files in the dat-folder save the zones -> all the blocks in them
You have some cauldrons in your zones which were previously saved as "cauldron" but can now be "water_cauldron" or something like that.

**Comment by Jakllp** [comment]
Did it work?

**Comment by JacksonWillford** [comment]
> Did it work?

Hey! Sorry I've been out for a bit due to the holidays. I'll be home next week! Sorry for the delay!!

**Comment by Jakllp** [comment]
All good, was just wondering ^^
